### ISSUE TITLE
use localStorage cache module

### ISSUE THREAD

**Issue by Negaihoshi** [i18next/i18nextify#13]
Can I use https://github.com/i18next/i18next-localStorage-cache module in i18nextify?

I saw some code https://github.com/i18next/i18nextify/blob/master/i18nextify.js#L553 about cache.
But it's not working.

My setting

``` js
window.i18nextify
  .init({
    debug: true,
    ns: ["translation"],
    autorun: true,
    ele: document.body,
    ignoreTags: ['SCRIPT'],
    namespace: false,
    namespaceFromPath: false,

    lngs: ['en', 'zh_TW', 'ja', 'zh_CN'],
    fallbackLng: "zh_TW",
    saveMissing: false,

    preload: ['zh_TW', 'en', 'ja', 'zh_CN'],
    backend: {
      loadPath: path
    },
    cache: {
      enabled: true,
      prefix: 'i18next_res_',
      expirationTime: 7 * 24 * 60 * 60 * 1000
    }
  });
```

**Comment by jamuhl** [comment]
you can...i18nextify exposes its i18next instance:

```
window.i18nextify.i18next.use(window.i18nextLocalStorageCache);
window.i18nextify.init({....});
```

**Comment by jamuhl** [comment]
By the way, we work on a new solution for using i18next, i18nextify serverless by providing a backend solution and services for translating the content.

You might checkout http://locize.com - we're currently in closed beta. If you're interested we would be able to get you onboard.

**Comment by Negaihoshi** [comment]
@jamuhl It's work!
Thanks you.

Locize looks great, I will wait it release to try it.
