### ISSUE TITLE
window.i18nextify.init({}) callback

### ISSUE THREAD

**Issue by vaiulian** [i18next/i18nextify#79]
Hi,

i found this really nice i18nextify lib that is kinda working for me right now. 

But i do have a question. It seems that my callback from the .init doesn't gets called. 

window.i18nextify.init({
    debug: false,
    lng: language,
    fallbackLng: 'en-US',
    namespace: 'login',
    ignoreTags: ['SCRIPT'],
    translateAttributes: ['placeholder', 'title', 'alt', 'value#input.type=button', 'value#input.type=submit']
}, function() {
    findErrorCookie();
});

that `findErrorCookie` never runs, actually nothing get called in the callback. Am i doing this the wrong way?

Thanks

**Comment by jamuhl** [comment]
there is no such callback for init done - but https://github.com/i18next/i18nextify/blob/master/src/index.js#L33 you might use...get triggered on first translate

**Comment by vaiulian** [comment]
@jamuhl you are right.

I tried the i18nextify.i18next.init({ but that overrides the nextify completely.

waitForInitialRender does work for my corner case, because is really fast. Maybe if it would take more i guess i would have issues with it. but it's ok for now.

Thanks.

**Comment by jamuhl** [comment]
if you need more we can take a look again...we could add a possible callback here: https://github.com/i18next/i18nextify/blob/master/src/index.js#L170
