### ISSUE TITLE
json-files not loading on certain pages

### ISSUE THREAD

**Issue by cielito-lindo-productions** [i18next/i18nextify#81]
Hi,
I integrated i18nextify on my page and it is working fine. Unfortunately on some pages the json files can't get loaded (eg. https://www.cielitolindo.de/pages/about/)
Console says 
i18next::backendConnector: loading namespace translation for language de failed failed parsing /storage/plugins/koken-multilanguage/assets/locales//.json to json  i18nextify_lessconsoleoutput.min.js:1:18190
i18next::backendConnector: loading namespace translation for language en failed failed parsing /storage/plugins/koken-multilanguage/assets/locales//.json to json  i18nextify_lessconsoleoutput.min.js:1:18190
i18next: languageChanged de  i18nextify_lessconsoleoutput.min.js:1:18190
i18next: initialized Object { debug: "true", initImmediate: true, ns: Array[1], defaultNS: "translation", fallbackLng: Array[1], fallbackNS: false, whitelist: false, nonExplicitWhitelist: false, load: "all", preload: false, 36 more… }

Although the main page https://www.cielitolindo.de is loading the json-files fine.

What can I do to solve this issue?

Greetings
CLP

**Comment by adrai** [comment]
Are you sure you are fetching a json file?
Seems like you are getting a redirect (302) to /error/404/ and this is a `<html...`
Make sure you are serving your translations files in the correct path... is this correct? "/storage/plugins/koken-multilanguage/assets/locales//.json"

**Comment by adrai** [comment]
Have just seen on your main page the path is configured like this:
```javascript
...
	backend: {
	      // for all available options read the backend's repository readme file
	      loadPath: '/storage/plugins/koken-multilanguage/assets/locales/{{lng}}/{{ns}}.json',
	}
...
```

**Comment by cielito-lindo-productions** [comment]
Hi,
thanks for your comments.
the loadPath I use is working correctly on the main page cielitolindo.de and json-files are retrieved correctly from eg. https://cielitolindo.de/storage/plugins/koken-multilanguage/assets/locales/de/translation.json

{{lng}} is replaced correctly by i18nextify to de and {{ns}} to translation.
Somehow **replacing the placeholders on the about page doesn't work.**

The console output of the main page is
i18next::backendConnector: loaded namespace translation for language de Object { Contact: "Kontakt", Albums: "Alben", About: "Über", Imprint & Privacy Policy: "Impressum & Datenschutzerklärung", Cielito Lindo Productions: "Cielito Lindo Productions", Home: "Home", 120 more… }  i18nextify.js:24:36
i18next::backendConnector: loaded namespace translation for language en Object { Contact: "Contact", Albums: "Albums", About: "About", Imprint & Privacy Policy: "Imprint & Privacy Policy", Cielito Lindo Productions: "Cielito Lindo Productions", Home: "Home", 120 more… }  i18nextify.js:24:36
i18next: languageChanged de  i18nextify.js:24:36
i18next: initialized Object { debug: "true", initImmediate: true, ns: Array[1], defaultNS: "translation", fallbackLng: Array[1], fallbackNS: false, whitelist: false, nonExplicitWhitelist: false, load: "all", preload: false, 36 more… }

**Comment by jamuhl** [comment]
adriano meant your html is:

```

	window.i18nextify.i18next.use(i18nextBrowserLanguageDetector);
	var languageDetectorOptions = 
	{
	// order and from where user language should be detected
	order: ['querystring', 'cookie', 'localStorage', 'navigator', 'htmlTag'],
	// keys or params to lookup language from
	lookupQuerystring: 'lng',
	lookupCookie: 'i18next',
	lookupLocalStorage: 'i18nextLng',
	// cache user language on
	caches: ['localStorage', 'cookie'],
	excludeCacheFor: ['cimode'], // languages to not persist (cookie, localStorage)
	// optional expire and domain for set cookie
	cookieMinutes: 60,
	cookieDomain: 'myDomain',
	// optional htmlTag with lang attribute, the default is:
	htmlTag: document.documentElement
	};
	window.i18nextify.i18next.use(window.i18nextLocalStorageCache);
	var cacheOptions =
	{
	enabled: false,
	prefix: 'i18next_res_',
	expirationTime: 24 * 60 * 60 * 1000 // in seconds
	};
	var translation = window.i18nextify
	.init({
	debug: 'true',
	saveMissing: 'true',
	namespace: 'translation',
	fallbackLng: 'en',
	detector: languageDetectorOptions,
	cache: cacheOptions,
	ignoreTags: ['script','img','noscript', 'alt', 'src'],
	ignoreIds: ['ignoreMeId','noscript', 'alt', 'src'],
	ignoreClasses: ['ignoreMeClass','noscript', 'alt', 'src'],
	backend: {
	      // for all available options read the backend's repository readme file
	      loadPath: '/storage/plugins/koken-multilanguage/assets/locales//.json',
	}
	});
	
```

see `backend.loadPath` should have `{{lng}}`, `{{ns}}`:

loadPath: '/storage/plugins/koken-multilanguage/assets/locales/{{lng}}/{{ns}}.json',

**Comment by cielito-lindo-productions** [comment]
the html code is loadPath: '/storage/plugins/koken-multilanguage/assets/locales/{{lng}}/{{ns}}.json',
the problem in my view is that i18nextify replaces {{lng}} and {{ns}} replaces with empty strings instead of filling with de and translation.

You can see the code [here](https://github.com/cielito-lindo-productions/koken-multilanguage) in the file plugin.php
The plugin is for koken which is a CMS for pictures.

**Comment by jamuhl** [comment]
i18next does not replace those values: https://github.com/i18next/i18next-xhr-backend/blob/master/src/index.js#L44 -> does not set/overwrite the value

**Comment by cielito-lindo-productions** [comment]
I'm using i18nextify, the strange thing is that it is working on the main page,  the values are replaced and therefore the correct json retrieved.
Do I then need to integrate xhr in my code?

**Comment by jamuhl** [comment]
that module is bundled with i18nextify already

i18nextify is basically: i18next, xhr-backend, browserlanguagedetector + vdom

**Comment by jamuhl** [comment]
really very sure that's your code doing a overwrite there. i18next use that url to load multiple files so would not work if it would remove those vars. i18nextify does not touch script tags.

**Comment by cielito-lindo-productions** [comment]
okay, I understand. Before reading your last post I was about to ask you if  can you guide me a bit what I need to do in order to get the proper replacement of {{lng}} and {{ns}} on all pages? But reading that koken might be replacing i18next-stuff there's probably not much you  can do...

I was trying to work around the missing replacement by using translation caching (as you can see in my code). This was working well on eg. Firefox (the strings were loaded from the cache although the json files couldn't be loaded) but somehow on Opera (on ubuntu) caching was not working and the page anyhow tried to retrieve the json-files (which does not work on the about page) and therefore no translation was available.

**Comment by jamuhl** [comment]
yes...really sorry but looking at your pages:

https://www.cielitolindo.de/pages/about/
<img width="662" alt="screen shot 2017-10-19 at 22 08 02" src="https://user-images.githubusercontent.com/977772/31791774-0691975e-b51a-11e7-929a-7742d4cb21e1.png">

vs

https://www.cielitolindo.de/
<img width="692" alt="screen shot 2017-10-19 at 22 07 42" src="https://user-images.githubusercontent.com/977772/31791794-16a3606e-b51a-11e7-84f4-01eb2953f10e.png">

it's really obvious something wents wrong in backend

**Comment by cielito-lindo-productions** [comment]
Now if I think it double you are probably right with the fact that koken replaces i18nextify stugg. In fact koken uses in the php code {{ }} for variables. see [the documentation]](http://help.koken.me/customer/en/portal/articles/982033-lens-variables)
Is it possible to replace {{ns}} by something more specific eg. {{i18nextifyns}} or even {[i18nextify]}?

**Comment by jamuhl** [comment]
hm...you could try setting those {{}} to __ __ and use 

loadPath: '/storage/plugins/koken-multilanguage/assets/locales/\_\_lng\_\_/\_\_ns\_\_.json'

with additional init options:

```
.init({
  interpolation: { prefix: '__', suffix: '__' },
  // your other settings
})
```

**Comment by cielito-lindo-productions** [comment]
Awesome man, seems that it's working now.
Although I included __ in the load path (you had it without in your post)
loadPath: '/storage/plugins/koken-multilanguage/assets/locales/__lng__/__ns__.json'
I'll do some more intense testing and then close this defect.
I really appreciate your help!

**Comment by jamuhl** [comment]
argh...markdown yes should not be bold - that should be two underlines...need to escape that

**Comment by cielito-lindo-productions** [comment]
seems to work now, therefore I closed the issue. Thanks again

**Comment by jamuhl** [comment]
you're welcome

**Comment by jamuhl** [comment]
if you ever like an upgrade on the translation management side you might have a look at our service tier: https://locize.com
