### ISSUE TITLE
question about the mutationObserver

### ISSUE THREAD

**Issue by vjustov** [i18next/i18nextify#82]
Hello, thanks for your wonderful work with this library.

Im using a particular squarespace layout and when using certain component i18nextify is unable to translate the content. While debugging i noticed that it was looking for the image tag as the key, but setting that in the translation does not work either.

How does the mutationObserver work? 

If you scroll down to the about us part of the page https://www.edelwiis.ch/?lng=en-US you will see that is still in German.

**Comment by jamuhl** [comment]
seems to me you have a wrong key in your setup:

if i call https://www.edelwiis.ch/?lng=en-US all works and i get following resources:
<img width="1279" alt="screen shot 2017-12-02 at 10 54 07" src="https://user-images.githubusercontent.com/977772/33514165-496712a0-d74f-11e7-8242-fd3904f2165c.png">

calling https://www.edelwiis.ch/home i get:
<img width="1279" alt="screen shot 2017-12-02 at 10 52 58" src="https://user-images.githubusercontent.com/977772/33514168-6240294c-d74f-11e7-9f8c-7b4e6c37eca4.png">

see the wrong key `Erin und Lauren Juon,   die Inhaberinnen ...` should be `die Inhaberinnen ...`

**Comment by jamuhl** [comment]
closing this for now...feel free to reopen if needed
