### ISSUE TITLE
Text Node Not Wrapped Inside a HTML Tag Does Not Get Translated

### ISSUE THREAD

**Issue by suhailga** [i18next/i18nextify#90]
If a text is not wrapped around an HTML tag, it does not get translated. Consider the following HTML snippet

```
<span>brian silas</span>
brian silas
<p>hello</p>

```
Here the key `brian silas` inside `span` tag gets translated, key `hello` inside `p` tag gets translated. But the key `brian silas` which is not wrapped around any HTML tag does not get translated. Although `brian silas` is not wrapped around any HTML tag, it is still a text node and must be translated by the library.

Here is also the linked sandbox: https://codesandbox.io/s/billowing-frog-y6hvs?file=/index.html

<img width="643" alt="Screenshot 2020-12-25 at 8 23 05 PM" src="https://user-images.githubusercontent.com/2191040/103137772-0e3f6e00-46f2-11eb-983e-7ad5a4eea854.png">

Note the orphan `brian silas` marked in red. Although it is not wrapped inside a HTML tag, it is still a valid HTML Text Node.

**Comment by jamuhl** [comment]
The vdom renderers and mutation observers get appended to root elements -> "to make the magic happen"

As text nodes are limited in not providing those you will need to wrap your content in an outer element.

```html
  <div>
    <p i18next-key="this is a test string">
      this is a test page.
    </p>

    <p>
      this is a test string
    </p>

    <h1>Yeh dhoop kinara</h1>
    <span>Brian Silas</span>
    <span>brian silas</span>
    <br />
    brian silas
    <br />
    <br />
    <button id="btn">Hindi</button>
    <button id="btn-2">Punjabi</button>
  </div>
```
