### ISSUE TITLE
<html> element must have a lang attribute

### ISSUE THREAD

**Issue by tvlc** [i18next/i18nextify#93]
## 🚀 Feature Proposal

According to standard, <html> element must have a lang attribute

## Motivation

See the description here:
https://www.w3.org/WAI/WCAG21/Techniques/html/H57.html
https://dequeuniversity.com/rules/axe/4.8/html-has-lang

**Comment by adrai** [comment]
https://github.com/i18next/i18nextify/blob/4a9ae6046c220fbc1a028a29bf5f217771d5d327/src/index.js#L174

**Comment by tvlc** [comment]
> https://github.com/i18next/i18nextify/blob/4a9ae6046c220fbc1a028a29bf5f217771d5d327/src/index.js#L174

Thank you!
