### ISSUE TITLE
Dom level auto translation with dropdown option to select all supported language

### ISSUE THREAD

**Issue by bsde1234** [i18next/i18nextify#95]
Please give code for dom level auto translation for static website with dropdown selection of language and remember selection in the browser local storage.

**Comment by jamuhl** [comment]
If you like just point me to your repository and I will do all the work for you - I not even ask for anything in return....please let me work for you

**Comment by bsde1234** [comment]
https://github.com/bsde1234/lfhcentre/

**Comment by jamuhl** [comment]
seems like you didn't get that the code is here in this repo...you did not get my irony...

idk....why you don't read through the readme of this repo, or i18next documentation...do you really expect to get the work done magically?
